id: P009125
initial_creation_type: ocr
source_metadata:
  id: bdr:W10314
  title: གསང་འདུས་ཆོས་འབྱུང
  author: ''
  volumes:
    16a8fb760e6347c9884646105c8b7c6f:
      image_group_id: I1611
      title: ''
      volume_number: 1
      total_pages: 519
