id: I4F1FBA5F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T07:44:00+00:00'
last_modified: '2022-06-08T08:48:09.137157+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W10314
  title: གསང་འདུས་ཆོས་འབྱུང
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '3107':
      image_group_id: I1611
      title: ''
      total_pages: 519
      order: 1
      base_file: 3107.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
